version: "2"
services:

  rtorrent:
    build: 
      context: https://github.com/StayPirate/alpine-rtorrent.git
      args:
        - UGID=${RTORRENT_UID}
    image: alpine-rtorrent:local
    container_name: seedbox-rtorrent
    volumes:
      - rtorrent_session:/home/rtorrent/rtorrent/.session
      - download:/home/rtorrent/rtorrent/download
    networks:
      rtorrent_vlan:
        aliases:
          - rtorrent
        ipv4_address: 172.16.60.3
    restart: always

  flood:
    build: https://github.com/jfurrow/flood.git
    image: flood:local
    container_name: seedbox-flood
    volumes:
      - flood_data:/data
    networks:
      rtorrent_vlan:
        aliases:
          - flood
        ipv4_address: 172.16.60.2
    restart: always
    depends_on:
      - rtorrent

volumes:
   rtorrent_session:
   download:
     driver: local
     driver_opts:
       type: cifs
       device: ${SHARE_PATH}
       o: username=${SHARE_USER},password=${SHARE_PASS},gid=${RTORRENT_UID},file_mode=0774,dir_mode=0774
   flood_data:

networks:
  rtorrent_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0.60
    ipam:
      config:
        - subnet: 172.16.60.0/29
          gateway: 172.16.60.1
