version: "2"
services:

  rtorrent:
    build: 
      context: https://github.com/StayPirate/alpine-rtorrent.git
      args:
        - UGID=${RTORRENT_UID}
    image: alpine-rtorrent:local
    ports:
      - "50000:50000"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - rtorrent_session:/home/rtorrent/rtorrent/.session
      - download:/home/rtorrent/rtorrent/download
    networks:
      rtorrent_net:
        aliases:
          - rtorrent
    restart: always

  flood:
    build: https://github.com/jfurrow/flood.git
    image: flood:local
    ports:
      - "80:3000"
    volumes:
      - flood_data:/data
    networks:
      rtorrent_net:
        aliases:
          - flood
    restart: always
    depends_on:
      - rtorrent

volumes:
   rtorrent_session:
   download:
     driver: local
     driver_opts:
       type: cifs
       device: ${SHARE_PATH}
       o: username=${SHARE_USER},password=${SHARE_PASS},gid=${RTORRENT_UID},file_mode=0774,dir_mode=0774
   flood_data:

networks:
  rtorrent_net:
    ipam:
      config:
        - subnet: 192.168.201.0/29
