version: "3.5"
services:

  rtorrent:
    build: https://github.com/StayPirate/alpine-rtorrent.git
    image: alpine-rtorrent:local
    ports:
      - "50000:50000"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - rtorrent_session:/home/rtorrent/rtorrent/.session
      - download:/home/rtorrent/rtorrent/download
    networks:
      rtorrent_net:
        aliases:
          - rtorrent

  flood:
    build: https://github.com/jfurrow/flood.git
    image: flood:local
    ports:
      - "80:3000"
    volumes:
      - flood_data:/data
    networks:
      rtorrent_net:
        aliases:
          - flood
    depends_on:
      - rtorrent

volumes:
   rtorrent_session:
   download:
     driver: local
     driver_opts: 
       type: cifs
       device: ${SHARE_PATH}
       o: username=${SHARE_USER},password=${SHARE_PASS},file_mode=0777,dir_mode=0777
   flood_data:

networks:
  rtorrent_net:
    name: rtorrent_net
    ipam:
      config:
        - subnet: 192.168.201.0/29
